version: "3.3"
services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    depends_on:
      - rabbitmq
      - redis
      - celery_worker
    volumes:
      - .:/app:z
    restart: on-failure
    ports:
      - 127.0.0.1:8008:8000

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      bash -c "
        sleep 5 &&
        watchmedo auto-restart --recursive --directory=/app --pattern=*.py \
          -- celery -A django_example.celery worker -l INFO"
    tty: true
    deploy:
      mode: replicated
      replicas: 2
    depends_on:
      - rabbitmq
      - redis
      - flower
    volumes:
      - .:/app:z

  flower:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      bash -c "
        sleep 5 &&
        celery -A django_example.celery flower \
          --address=0.0.0.0 \
          --port=5555 \
          --broker_api=http://guest@rabbitmq:15672/api/vhost"
    depends_on:
      - rabbitmq
      - redis
    volumes:
      - .:/app:z
    ports:
      - 127.0.0.1:5555:5555

  rabbitmq:
    image: rabbitmq:3-management

  redis:
    image: redis:6
