version: "3.3"
services:
  celery_service:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    depends_on:
      - redis
      - celery_worker
    volumes:
      - .:/app:z

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: watchmedo auto-restart --directory=/app --pattern=*.py -- celery -A tasks worker --loglevel=INFO
    tty: true
    depends_on:
      - redis
    volumes:
      - .:/app:z

  redis:
    image: redis:6
